#!/usr/bin/env bash
set -euo pipefail

# scripts/build-wazuh-bundle.sh
# Build a single deployable Wazuh rules file from the repo's individual XML rule files.
#
# Source (repo): detection-rules/wazuh/_incoming/WAZUH_RULES_PRIMARY/*.xml
# Output (default): dist/wazuh/local_rules.xml
#
# Usage:
#   ./scripts/build-wazuh-bundle.sh
#   ./scripts/build-wazuh-bundle.sh /tmp/local_rules.xml

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_DIR="${REPO_ROOT}/detection-rules/wazuh/_incoming/WAZUH_RULES_PRIMARY"
OUT_FILE="${1:-${REPO_ROOT}/dist/wazuh/local_rules.xml}"

if [[ ! -d "${SRC_DIR}" ]]; then
  echo "ERROR: Source directory not found: ${SRC_DIR}" >&2
  exit 1
fi

mapfile -t RULE_FILES < <(find "${SRC_DIR}" -maxdepth 1 -type f -name "*.xml" | LC_ALL=C sort)

if [[ "${#RULE_FILES[@]}" -eq 0 ]]; then
  echo "ERROR: No XML rules found under: ${SRC_DIR}" >&2
  exit 1
fi

mkdir -p "$(dirname "${OUT_FILE}")"

tmp="$(mktemp)"
{
  echo "<!--"
  echo "  Generated by scripts/build-wazuh-bundle.sh"
  echo "  Source: ${SRC_DIR}"
  echo "  Generated (UTC): $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "-->"
  echo

  for f in "${RULE_FILES[@]}"; do
    base="$(basename "${f}")"
    echo "<!-- SOURCE FILE: ${base} -->"
    # Drop UTF-8 BOM (if present) and drop any XML declaration line to avoid invalid concatenation.
    sed '1s/^\xEF\xBB\xBF//' "${f}" | sed '/^[[:space:]]*<\?xml[[:space:]].*\?>[[:space:]]*$/d'
    echo
  done
} > "${tmp}"

mv "${tmp}" "${OUT_FILE}"
chmod 0644 "${OUT_FILE}" 2>/dev/null || true

echo "✅ Wrote bundle: ${OUT_FILE}"
echo
echo "Next on your Wazuh manager:"
echo "  sudo cp \"${OUT_FILE}\" /var/ossec/etc/rules/local_rules.xml"
echo "  sudo systemctl restart wazuh-manager"
echo "  sudo tail -n 80 /var/ossec/logs/ossec.log | grep -i -E 'rule|local_rules'"
