# scripts/build-wazuh-bundle.ps1
# Build a single deployable Wazuh rules file from the repo's individual XML rule files.
#
# Source (repo): detection-rules/wazuh/rules/*.xml
# Output (default): dist/wazuh/local_rules.xml
#
# Usage:
#   .\scripts\build-wazuh-bundle.ps1
#   .\scripts\build-wazuh-bundle.ps1 -OutputFile "C:\custom\path\local_rules.xml"

[CmdletBinding()]
param(
    [string]$OutputFile = "dist\wazuh\local_rules.xml"
)

$ErrorActionPreference = "Stop"

# Get repo root
$RepoRoot = Split-Path -Parent $PSScriptRoot
$SrcDir = Join-Path $RepoRoot "detection-rules\wazuh\rules"
$OutFile = Join-Path $RepoRoot $OutputFile

# Validate source directory
if (-not (Test-Path $SrcDir)) {
    Write-Error "ERROR: Source directory not found: $SrcDir"
    exit 1
}

# Get all XML rule files
$RuleFiles = Get-ChildItem -Path $SrcDir -Filter "*.xml" -File | Sort-Object Name

if ($RuleFiles.Count -eq 0) {
    Write-Error "ERROR: No XML rules found under: $SrcDir"
    exit 1
}

# Create output directory if needed
$OutDir = Split-Path -Parent $OutFile
if (-not (Test-Path $OutDir)) {
    New-Item -ItemType Directory -Path $OutDir -Force | Out-Null
}

# Build bundle
$timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

$bundle = @"
<!--
  Generated by scripts/build-wazuh-bundle.ps1
  Source: $SrcDir
  Generated (UTC): $timestamp
-->

"@

foreach ($file in $RuleFiles) {
    $bundle += @"
<!-- SOURCE FILE: $($file.Name) -->
"@

    # Read content and strip XML declarations to avoid conflicts
    $content = Get-Content $file.FullName -Raw
    # Remove UTF-8 BOM if present
    $content = $content -replace "^\xEF\xBB\xBF", ""
    # Remove XML declaration lines
    $content = $content -replace '(?m)^\s*<\?xml\s+.*?\?>\s*$', ''

    $bundle += $content + "`n`n"
}

# Write bundle
[System.IO.File]::WriteAllText($OutFile, $bundle, [System.Text.Encoding]::UTF8)

Write-Host ""
Write-Host "✅ Wrote bundle: $OutFile" -ForegroundColor Green
Write-Host ""
Write-Host "Next on your Wazuh manager:"
Write-Host "  sudo cp `"$OutFile`" /var/ossec/etc/rules/local_rules.xml"
Write-Host "  sudo systemctl restart wazuh-manager"
Write-Host "  sudo tail -n 80 /var/ossec/logs/ossec.log | grep -i -E 'rule|local_rules'"
Write-Host ""
